version: '3.7'
services:
    db:
        image: postgres:12
        env_file: .env
    web:
        build: 
            context: .
        command: ["python", "manage.py", "runserver", "0:8000"]
        env_file: .env
        ports:
            - "8000:8000"
        volumes:
            - ./portfolio:/portfolio
        depends_on:
            - db